---
- hosts: proxmox1
  become: True
  tasks:
  - name: Cloning virtual machine 
    proxmox_kvm:
      api_user : root@pam
      api_password: 27942794
      api_host : 192.168.1.99
      name : Ansible
      node : pve
      clone: deploy
      timeout: 300
  - name: Loading set up for Virtual Machine. Assigning IP automatically, sockets, cores and memory for Virtual Machine
    shell: A=$(qm list | grep "Ansible"  | awk '{print $1}'); qm set $A -memory 3072 -sockets 1 -cores 1
  - name: Increasing disk if it is necessary
    shell: A=$(qm list |grep Ansible | awk '{print $1}'); qm resize $A virtio0 +10G
  - name: Waiting to apply cloud init changes in disk
    wait_for:
      timeout: 5
  - name: starting new Virtual Machine to change IPv4 configuration, it is necessary
    proxmox_kvm:
      api_user : root@pam
      api_password: 27942794
      api_host : 192.168.1.99
      name : Ansible
      node : pve
      state : started
      timeout: 300
    register: wait
  - name: Waiting to start virtual server machine completely
    wait_for:
      timeout: 120
    when: wait.changed == true
